[profile.default]
src = "contracts"
out = "artifacts"
libs = ["node_modules"]
remappings = [
    "forge-std/=node_modules/forge-std/src/"
]

[profile.test]
hardfork = "cancun"
fork_url = "${ARBITRUM_SEPOLIA_RPC_URL}"

[fmt]
line_length = 120
wrap_comments = true